services:
  mysql:
    image: mysql:8.0
    container_name: asset_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: smart_asset_management
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: asset_user
      MYSQL_PASSWORD: asset_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: asset_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: