<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Alerts Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
            margin: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            color: #2c3e50;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        thead {
            background-color: #34495e;
            color: white;
        }
        th {
            padding: 12px;
            text-align: left;
            border: 1px solid #ddd;
            font-weight: bold;
        }
        td {
            padding: 10px;
            border: 1px solid #ddd;
        }
        tbody tr:nth-child(even) {
            background-color: #ecf0f1;
        }
        .severity-critical {
            color: #c0392b;
            font-weight: bold;
        }
        .severity-high {
            color: #e67e22;
            font-weight: bold;
        }
        .severity-medium {
            color: #f39c12;
            font-weight: bold;
        }
        .severity-low {
            color: #27ae60;
            font-weight: bold;
        }
        .status-unread {
            color: #c0392b;
            font-weight: bold;
        }
        .status-read {
            color: #f39c12;
            font-weight: bold;
        }
        .status-resolved {
            color: #27ae60;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 12px;
        }
        .summary {
            margin-bottom: 20px;
            background-color: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
        }
        .summary p {
            margin: 5px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Alerts Report</h1>
        <p>Smart Asset Management System</p>
        <p>Generated: {{ $generatedAt->format('d F Y H:i:s') }}</p>
    </div>

    <div class="summary">
        <p><strong>Total Alerts:</strong> {{ $alerts->count() }}</p>
        <p>
            <strong>Critical:</strong> {{ $alerts->where('severity', 'critical')->count() }} |
            <strong>High:</strong> {{ $alerts->where('severity', 'high')->count() }} |
            <strong>Medium:</strong> {{ $alerts->where('severity', 'medium')->count() }} |
            <strong>Low:</strong> {{ $alerts->where('severity', 'low')->count() }}
        </p>
        <p>
            <strong>Unread:</strong> {{ $alerts->where('status', 'unread')->count() }} |
            <strong>Read:</strong> {{ $alerts->where('status', 'read')->count() }} |
            <strong>Resolved:</strong> {{ $alerts->where('status', 'resolved')->count() }}
        </p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Asset</th>
                <th>Type</th>
                <th>Severity</th>
                <th>Status</th>
                <th>Triggered At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($alerts as $alert)
            <tr>
                <td>{{ $alert->title }}</td>
                <td>{{ $alert->asset->name ?? '—' }}</td>
                <td>{{ str_replace('_', ' ', ucfirst($alert->alert_type)) }}</td>
                <td>
                    <span class="severity-{{ $alert->severity }}">
                        {{ ucfirst($alert->severity) }}
                    </span>
                </td>
                <td>
                    <span class="status-{{ $alert->status }}">
                        {{ ucfirst($alert->status) }}
                    </span>
                </td>
                <td>{{ $alert->triggered_at->format('d M Y H:i:s') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report is confidential and generated by the Smart Asset Management System.</p>
    </div>
</body>
</html>
