<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Assets Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
            margin: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            color: #2c3e50;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        thead {
            background-color: #34495e;
            color: white;
        }
        th {
            padding: 12px;
            text-align: left;
            border: 1px solid #ddd;
            font-weight: bold;
        }
        td {
            padding: 10px;
            border: 1px solid #ddd;
        }
        tbody tr:nth-child(even) {
            background-color: #ecf0f1;
        }
        .status-active {
            color: #27ae60;
            font-weight: bold;
        }
        .status-maintenance {
            color: #f39c12;
            font-weight: bold;
        }
        .status-retired {
            color: #e74c3c;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 12px;
        }
        .summary {
            margin-bottom: 20px;
            background-color: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
        }
        .summary p {
            margin: 5px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Assets Report</h1>
        <p>Smart Asset Management System</p>
        <p>Generated: {{ $generatedAt->format('d F Y H:i:s') }}</p>
    </div>

    <div class="summary">
        <p><strong>Total Assets:</strong> {{ $assets->count() }}</p>
        <p><strong>Active Assets:</strong> {{ $assets->where('status', 'active')->count() }}</p>
        <p><strong>Under Maintenance:</strong> {{ $assets->where('status', 'maintenance')->count() }}</p>
        <p><strong>Retired:</strong> {{ $assets->where('status', 'retired')->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Asset Code</th>
                <th>Name</th>
                <th>Category</th>
                <th>Department</th>
                <th>Status</th>
                <th>Assigned Device</th>
                <th>Purchase Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($assets as $asset)
            <tr>
                <td>{{ $asset->asset_code }}</td>
                <td>{{ $asset->name }}</td>
                <td>{{ $asset->category->name ?? '—' }}</td>
                <td>{{ $asset->department->name ?? '—' }}</td>
                <td>
                    <span class="status-{{ $asset->status }}">
                        {{ ucfirst($asset->status) }}
                    </span>
                </td>
                <td>{{ $asset->activeAssignment->trackerDevice->device_name ?? 'Not assigned' }}</td>
                <td>{{ $asset->purchase_date ? $asset->purchase_date->format('d M Y') : '—' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report is confidential and generated by the Smart Asset Management System.</p>
    </div>
</body>
</html>
