<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Tracking Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
            margin: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            color: #2c3e50;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 11px;
        }
        thead {
            background-color: #34495e;
            color: white;
        }
        th {
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
            font-weight: bold;
        }
        td {
            padding: 8px;
            border: 1px solid #ddd;
        }
        tbody tr:nth-child(even) {
            background-color: #ecf0f1;
        }
        .motion-yes {
            color: #27ae60;
            font-weight: bold;
        }
        .motion-no {
            color: #95a5a6;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 12px;
        }
        .summary {
            margin-bottom: 20px;
            background-color: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
        }
        .summary p {
            margin: 5px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Tracking History Report</h1>
        <p>Smart Asset Management System</p>
        <p>Generated: {{ $generatedAt->format('d F Y H:i:s') }}</p>
    </div>

    <div class="summary">
        <p><strong>Total Entries:</strong> {{ $logs->count() }}</p>
        <p>
            <strong>Date Range:</strong>
            {{ $logs->min('recorded_at') ? \Carbon\Carbon::parse($logs->min('recorded_at'))->format('d M Y') : '—' }}
            to
            {{ $logs->max('recorded_at') ? \Carbon\Carbon::parse($logs->max('recorded_at'))->format('d M Y') : '—' }}
        </p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Asset</th>
                <th>Device</th>
                <th>Timestamp</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>Speed (km/h)</th>
                <th>Motion</th>
            </tr>
        </thead>
        <tbody>
            @foreach($logs as $log)
            <tr>
                <td>{{ $log->asset->name ?? '—' }}</td>
                <td>{{ $log->trackerDevice->device_name ?? '—' }}</td>
                <td>{{ $log->recorded_at->format('d M Y H:i:s') }}</td>
                <td>{{ $log->latitude }}</td>
                <td>{{ $log->longitude }}</td>
                <td>{{ $log->speed ?? '—' }}</td>
                <td>
                    <span class="motion-{{ $log->motion_detected ? 'yes' : 'no' }}">
                        {{ $log->motion_detected ? 'Yes' : 'No' }}
                    </span>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report is confidential and generated by the Smart Asset Management System.</p>
    </div>
</body>
</html>
