<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class AlertRule extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
        'asset_type',
        'condition_type',
        'condition_value',
        'threshold_unit',
        'severity',
        'action_type',
        'notification_channels',
        'is_active',
        'created_by',
    ];

    protected $casts = [
        'notification_channels' => 'array',
        'is_active' => 'boolean',
    ];

    /**
     * Get the user who created this rule
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Get alerts generated by this rule
     */
    public function alerts(): HasMany
    {
        return $this->hasMany(Alert::class, 'rule_id');
    }

    /**
     * Evaluate if rule condition is met
     */
    public function evaluateCondition(mixed $value): bool
    {
        if (!$this->is_active) {
            return false;
        }

        return match ($this->condition_type) {
            'equals' => $value == $this->condition_value,
            'greater_than' => $value > $this->condition_value,
            'less_than' => $value < $this->condition_value,
            'greater_or_equal' => $value >= $this->condition_value,
            'less_or_equal' => $value <= $this->condition_value,
            'not_equal' => $value != $this->condition_value,
            'contains' => str_contains((string) $value, (string) $this->condition_value),
            'not_contains' => !str_contains((string) $value, (string) $this->condition_value),
            'in_range' => $this->evaluateRange($value),
            'regex' => preg_match($this->condition_value, (string) $value),
            default => false,
        };
    }

    /**
     * Evaluate range condition (format: "min,max")
     */
    private function evaluateRange(mixed $value): bool
    {
        $range = explode(',', $this->condition_value);
        if (count($range) !== 2) {
            return false;
        }

        [$min, $max] = $range;
        return $value >= (float) $min && $value <= (float) $max;
    }

    /**
     * Get applicable notification channels
     */
    public function getNotificationChannels(): array
    {
        return $this->notification_channels ?? ['email'];
    }

    /**
     * Toggle rule active status
     */
    public function toggle(): void
    {
        $this->update(['is_active' => !$this->is_active]);
    }

    /**
     * Get rule template name
     */
    public function getTemplate(): string
    {
        return match ($this->asset_type) {
            'vehicle' => 'Vehicle Alert Rule',
            'equipment' => 'Equipment Alert Rule',
            'device' => 'Device Alert Rule',
            default => 'Custom Alert Rule',
        };
    }
}
